### ISSUE TITLE
Public tree directory should be configurable

### ISSUE THREAD

**Issue by haclong** [laminas-api-tools/api-tools-asset-manager#19]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary
when i read Asset Manager documentation, it seems the asset of other packages are copied to the public tree which means the public/ directory

but in the case you still use shared hosting, sometimes, the public directory is htdocs/ or web/ then, the asset-manager can't help

we should be able to add in (for ex) global.conf.php a configuration entry kind of  
'asset-manager' => [
   'public-tree-directory' => 'htdocs'
]

**Comment by weierophinney** [comment]
Closing as "won't fix".

The skeleton assumes a scenario where the vhost is mapped to the `public/` tree, and adding support for this module to allow for a different directory would also mean adding support in the skeleton for a different directory, and that opens up a ton of support vectors we simply cannot agree to maintain.

**Comment by haclong** [comment]
that's fair
thank you @weierophinney
