### ISSUE TITLE
Broken interface api in composer v1

### ISSUE THREAD

**Issue by snapshotpl** [laminas-api-tools/api-tools-asset-manager#6]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.3.0

After update to 1.3.0 using `composer update`, I get an error:

```
Fatal error: Uncaught TypeError: Argument 1 passed to Laminas\ApiTools\AssetManager\AssetInstaller::__invoke() must implement interface Composer\Package\PackageInterface, instance of Composer\Installer\PackageEvent given, called in /var/www/vendor/laminas-api-tools/api-tools-asset-manager/src/Plugin.php on line 109 and defined in /var/www/vendor/laminas-api-tools/api-tools-asset-manager/src/AssetInstaller.php:61
Stack trace:
#0 /var/www/vendor/laminas-api-tools/api-tools-asset-manager/src/Plugin.php(109): Laminas\ApiTools\AssetManager\AssetInstaller->__invoke(Object(Composer\Installer\PackageEvent))
#1 /var/www/vendor/laminas-api-tools/api-tools-asset-manager/src/Plugin.php(74): Laminas\ApiTools\AssetManager\Plugin->Laminas\ApiTools\AssetManager\{closure}()
#2 [internal function]: Laminas\ApiTools\AssetManager\Plugin->onPostAutoloadDump(Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Composer\Script\Event))
#4 phar:///usr/ in /var/www/vendor/laminas-api-tools/api-tools-asset-manager/src/AssetInstaller.php on line 61
```

I'm using composer 1.10.7. Looks like introduced in #5 

@boesing @weierophinney

**Comment by boesing** [comment]
I know what is going on during migration of the package. But this usually only happens in local development or in projects where the `vendor/` directory is committed.

The thing is, that composer loads the local plugin from `vendor/` directory and registers the installers. 
As those installers are callables and the `AssetInstaller` / `AssetUninstaller` is created inside the callable, the class itself is not loaded for now. The callables are those from the version prior `1.3.0`.

After this, composer updates the package to `1.3.0` and the `post-autoload-dump` event is being triggered. During this event, those callbacks which were created from the composer-plugin (which was in version `1.2.0`) are instantiating the `AssetInstaller`/`AssetUninstaller` of `1.3.0` (which are still compatible).

Now, the `__invoke` method of `1.3.0` is not compatible anymore.

So there are two solutions for this while one does not include any hacks from our side:
1. Remove your vendor directory before calling `composer update laminas-api-tools/api-tools-asset-manager`
2. We remove typehint from `__invoke` until `2.0.0`, assuming that `PackageEvent` can be passed and extracting the package from the `PackageEvent` object (I've already done that in a local branch)

The latter will also require writing a migration guide for 2.0 where the user has to fully upgrade the minor version before upgrading to the next majors. 

@weierophinney What do you think? The most user-friendly option will be 2.0 as one can easily migrate in any edge-case (having old versions already installed in `vendor/`) but means more maintenance.

**Comment by snapshotpl** [comment]
2 options make sense

**Comment by boesing** [comment]
I've added a possible fix for this issue. However, I still don't know if thats a good trade.
